### ISSUE TITLE
Add Option to Open BBEs in the Playground

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1112]
**Description:**
We need to integrate the Ballerina Playground[1] with the BBEs[2] by adding an option on each BBE to open it in the Playground.

[1] https://play.ballerina.io/
[2] https://ballerina.io/learn/by-example/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lafernando** [comment]
Now, we have to provide an additional boolean parameter to the command to say whether to generate the Playground link or not. Example:-

go run ballerinaByExample/tools/generate.go "/home/laf/dev/ballerina-release/examples" "999" "by-examplex" "true" "true" "true"

The additional parameter is because, the Playground link generation adds a considerable overhead to the BBE generation, since it does a call through the Internet to Playground APIs. So for example, when we are testing locally for generating BBEs, we can disable this and test it. And only when we are doing the last generation of the BBEs, we can make the flag to "true" and run the tool.
