### ISSUE TITLE
Syntax highlighting in the release notes is not up-to-date with the language syntax

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#1339]
The syntax highlighting doesn't seem to be supporting the latest language syntax. e.g., class, distinct keywords

**Comment by praneesha** [comment]
This issue is there not only in the release notes pages but also in BBEs and Learn pages. The below are some examples:

[Release Notes pages:](https://ballerina.io/downloads/swan-lake-release-notes/)
<img width="1048" alt="Screenshot 2020-10-06 at 10 30 15" src="https://user-images.githubusercontent.com/11707273/95165131-00e8a680-07c9-11eb-9d35-335d3e87442e.png">

<img width="1074" alt="Screenshot 2020-10-05 at 20 55 14" src="https://user-images.githubusercontent.com/11707273/95165122-fd551f80-07c8-11eb-925e-321ce1b54f92.png">

[BBE Pages:](https://ballerina.io/learn/by-example/abstract-objects.html)

<img width="792" alt="Screenshot 2020-10-06 at 11 25 24" src="https://user-images.githubusercontent.com/11707273/95165237-3a211680-07c9-11eb-934e-7d9cbc25a82d.png">

[Learn Pages:](https://ballerina.io/learn/calling-java-code-from-ballerina/#external-interop-functions)

**Comment by praneesha** [comment]
@hevayo - Where do we need to make the updates to get these keywords highlighted?

**Comment by hevayo** [comment]
We update the prism grammar file with slp4. I guess you need to update the ballerina.io to use the updated grammar file.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/1409.
