### ISSUE TITLE
Need to update on where/how to add JDBC driver in ballerina sample [1.0.5]

### ISSUE THREAD

**Issue by himasha** [ballerina-platform/ballerina-dev-website#146]
**Description:**
In https://ballerina.io/learn/by-example/jdbc-client-crud-operations.html it states that the driver jar needs to be added to bal_home/bre/lib folder whereas https://ballerina.io/learn/api-docs/ballerina/java.jdbc/index.html explains the path to be specified in the .toml file. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
1.0.5
**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Those are the 2 different approaches that can be used to add the driver JAR file.

Since we run a single BAL file in BBEs, we have to add the driver JAR file to the "/.../lib" folder. However, since we run a module, we can configure the path of the driver JAR file in the TOML file of the module. 

This is explained in API Docs as follows.

<img width="1440" alt="Screenshot 2020-10-06 at 14 24 13" src="https://user-images.githubusercontent.com/11707273/95180529-bb83a380-07df-11eb-99fb-4eb01fddcd65.png">
