### ISSUE TITLE
Add the Homebrew Installation Option for Swan Lake in Bio

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1929]
**Description:**
Need to add the Homebrew installation option for Swan Lake (the ZIP file) in the Downloads and Installation pages once the implementation is complete.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Since we have not published for a while. Let's wait until we release GA as homebrew requires released artifacts to update the formulas (They do not support pre releases like beta). As we release GA we can point released artifacts in the live location for homebrew formula and update website content along with that.

**Comment by praneesha** [comment]
Closing as this is fixed now.
