### ISSUE TITLE
Installation JDBC driver not correctly documented since 1.1.0

### ISSUE THREAD

**Issue by fokkerispens** [ballerina-platform/ballerina-dev-website#200]
**Description:**
On: https://ballerina.io/learn/by-example/jdbc-client-crud-operations.html it says: "... copy the MySQL JDBC driver to the BALLERINA_HOME/bre/lib folder ...". This must be "... copy the MySQL JDBC driver to the BALLERINA_HOME/bre/lib/distributions/jballerina-[X.X.X]/bre/lib folder ..." in which [X.X.X] is the active versions of Ballerina.

Tested it with a Microsoft "mssql-jdbc-7.4.1.jre8.jar" to an Azure SQL database and it works. Logically the proposed correction in documentation will apply to all current working JDBC drivers.

**Suggested Labels:**
Documentation

**Suggested Assignees:**

**Affected Product Version:**
Ballerina 1.1.0 + 

**OS, Browser, other environment details and versions:**    
All

**Steps to reproduce:**
Not applicable

**Related Issues:**
Will probably be documented the old way on other places to. Search for bre/lib

**Comment by praneesha** [comment]
These were fixed in the respective repos via the PRs below.

1. https://github.com/ballerina-platform/ballerina-lang/pull/26231
2. https://github.com/ballerina-platform/ballerina-lang/pull/26233
3. https://github.com/ballerina-platform/ballerina-lang/pull/26234
4. https://github.com/ballerina-platform/ballerina-dev-website/pull/1363
5. https://github.com/ballerina-platform/ballerina-distribution/pull/857
6. https://github.com/ballerina-platform/module-ballerina-java.jdbc/pull/15
