### ISSUE TITLE
Couple of issues in bindgen doc

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-dev-website#2018]
**Description:**
Following issues were found in [Bingen](https://ballerina.io/learn/user-guide/calling-java-code-from-ballerina/) doc.

1. I think we have to mention the java version we need to use, not all versions will work for this feature.
2. It does not clear, why we put `The ‘bindgen’ Tool` topic after `Using the SnakeYAML Java Library in Ballerina` topic. It will be more clear if we can explain first the significance of bindgen tool, then explain the subcommand and finally add the example.  
3. Under `Step 4 - Writing the Ballerina Code` -> `Completing the Code`, mentioned code is not working because there is not a method called `load`, that should be renamed as `load1`.
4. Under `Step 4 - Writing the Ballerina Code` -> `Completing the Code`, it says to copy the code to a module called `yamlparser`. But is does not mentioned we have to create a module called `yamlparser`.

**Affected Product Version:**
slpalpha3

**Comment by IrushiL** [comment]
Issue numbers 3 and 4 are fixed in the guide.

As for issue number 1, since we have conveyed that this feature is based on the JVM used by jBallerina, we need not explicitly define Java versions, since it derived from the JVM version of jBallerina. However, we will keep a note as to whether further elaboration on this is actually needed. 

The decision to go ahead with an example before explaining the command in detail, as pointed out in the 2nd point, was mainly to not overburden the user with all the details and to go with the flow of information (need for interops, a simple example, an in-depth explanation on the command, etc.). I believe the explanations needed for the example scenario are clearly conveyed in each step.

Hence, we will be closing this issue and will re-open it if required.
