### ISSUE TITLE
Should we rename `Language Intelligence` to `Language IntelliSense`

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2194]
**Description:**
$subject in [1]

Referring to [2] 

[1] https://ballerina.io/learn/tooling-guide/visual-studio-code-extension/language-intelligence/
[2]  https://code.visualstudio.com/docs/editor/intellisense

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
@anupama-pathirage IntelliSense is a VSCode specific term, therefore I think it is okay to change it here only. Earlier we used this guide as a general term for both of our plugins, hence went for a common term `Language Intelligence`. Now, since the structure has been changed, I would like to suggest to go with `IntelliSense` only. WDYT?
