### ISSUE TITLE
Incomplete documentation around usage of `@strand` with asynchronous function calls

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#3276]
**Description:**
We can execute a function asynchronously on a different thread using `@strand {thread: "any"}` which is an important feature when it comes to achieving true parallelism. i.e, we can do the following:
```ballerina
future<error?> f = @strand{thread: "any"} start calculate(mat1, mat2, result, i, j);
```
But the Ballerina documentation around asynchronous function calls do not mention this capability.

TODO (Added by @KRVPerera): 
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/4816

**Describe your problem(s)**
See description

**Describe your solution(s)**
See description

**Comment by Nadeeshan96** [comment]
Since we are deprecating the `@strand` annotation with swan lake update 2, discussed not to include information about the annotation in the `strands` BBE. The `strands` BBE needs to be modified such that
- it does not contain the `@strand` annotation.
- it has an example to show, an asynchronous function call like `future<int> fut = start foo();` also runs on a separate strand.
- it mentions that now a strand will run a separate thread depending on isolation.

**Comment by KRVPerera** [comment]
The first two points are fixed by
- https://github.com/ballerina-platform/ballerina-distribution/pull/3000

For the last point, we discussed that making the strands BBE complex is not good. 
- https://github.com/ballerina-platform/ballerina-dev-website/issues/4816

**Comment by KRVPerera** [comment]
Closing the issue as tracked part of this here https://github.com/ballerina-platform/ballerina-dev-website/issues/4816
The new issue needs discussion before continuing and cannot guess whether we even need to add the details in a BBE.
