### ISSUE TITLE
Breadcrumbs are not shown in BBE pages

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#3354]
**Description:**
$subject

Without breadcrumbs, users have no idea how to return to the learn by example or reference by example pages. This is a major UX issue when trying to learn Ballerina.

**Steps to reproduce:**
Go to a BBE via reference by example page

**Comment by praneesha** [comment]
Closing since we will be having only one Ballerina By Example view after the Swan lake GA release and it will have breadcrumbs as shown below.

![Screenshot 2022-01-12 at 22 51 44](https://user-images.githubusercontent.com/11707273/149190310-42c3d792-424a-4ab5-a77c-a0dc91550902.png)

For example, see http://dev.ballerina.io/learn/by-example/multiple-key-fields.html.
