### ISSUE TITLE
Fix the zip file link for archived versions download

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#3753]
With Swan Lake GA, we changed the versioning scheme. With this, the `version` and `short-version` both are the same now. Because of that, the links to the zip files are pointing to the wrong zip file. Need to fix this before the next patch release.

**Comment by keizer619** [comment]
Yes now both are same and we create two zip files. One has update tool one does not have

- With update tool -> ballerina-2201.0.0-swan-lake.zip (earlier this was ballerina-swan-lake-beta6.zip)
- Without update tool -> ballerina-2201.0.0.zip (earlier this was ballerina-slbeta6.zip)

We need to make sure we point to ballerina-2201.0.0-swan-lake.zip from website always. This may point to other zip if construct the name ballerina-<version>.zip. In that case we need to include `swan-lake` part

**Comment by NipunaMadhushan** [comment]
There are two places where we can download the ballerina zip file.
1. Installer Options
2. Archived Versions

This is not an issue since `other-artifacts`  in the metadata.json file has been used to create the path for the ballerina zip url. the url will be like this.
https://dist-dev.ballerina.io/downloads/2201.0.1/ballerina-2201.0.1-swan-lake.zip
