### ISSUE TITLE
Need to improve or add new BBE for isolation inference and show how it affect strands

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-dev-website#4816]
## Description

We need to show how a strand runs on a separate thread based on isolation.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by Nadeeshan96** [comment]
Had a discussion with @lasinicl. This had been fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/3228, and the relevant BBEs are already there: https://ballerina.io/learn/by-example/inferring-isolated/, https://ballerina.io/learn/by-example/run-strands-safely-on-separate-threads/.
