### ISSUE TITLE
Subscribe to newsletter doesn't show success or error message

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#4834]
## Description
See the following screen capture:
![Peek 2022-07-25 15-06](https://user-images.githubusercontent.com/11285165/180746984-ecb196ac-9fba-47c7-8cc3-fb8e2c6429d3.gif)

I experience several issues here:
1. When I enter my email and submit, I get no error or success message
2. No error when license agreement is not checked
3. No error shown when google captcha is not ticked
4. The `privacy policy` link points to the live site (which is fine, but would have been better if the link is consistent with the privacy policy link in footer)

## Steps to reproduce
Try to subscribe to newsletter

## Affected version(s)
dev.ballerina.io

**Comment by dinushan20** [comment]
In this, Please find my answers below,

1. In the text box it give error if we don't include the email, Also reCaptcha also give error but this isn't visible, but after increasing height now we can see it. If we add email and check reCaptcha then it show success message
![image](https://user-images.githubusercontent.com/73055030/182788340-13c2d22a-1ba8-4f53-8c4a-ef6d52b10ea7.png)
![image](https://user-images.githubusercontent.com/73055030/182788510-eab1a311-8467-4cfd-a37d-e3ccf19d08c9.png)

2. It's not a mandatory field to checked by user, according to the GDPR policies, So it doesn't need error message
3. This one is visible, but it is visible in bottom not visible previously, But now iframe height has increased and now we can see the error.
4. Since it embed from iframe we can't put URL like "/privacy-policy" So we need to add full URL to redirect it.

**Comment by praneesha** [comment]
Closing as per the above comment.
