### ISSUE TITLE
Suggesting improvements to the Call Java Code from Ballerina page

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4915]
## Description
Suggesting a few changes to [1] to improve it.

[1] https://dev.ballerina.io/learn/call-java-code-from-ballerina/#Write%20Ballerina%20bindings

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Suggestions

1. Change the first paragraph as follows.

```suggestion
The `bindgen` is a CLI tool that eases the process of generating Ballerina bindings for given Java APIs. This guide shows you how to use it. For more details on how the `bindgen` tool works, see [Bindgen Tool](https://dev.ballerina.io/learn/java-interoperability-guide/the-bindgen-tool/).
```

This is because:

- "Which" is used instead of that. This issue is present in several places in this page as well as in other pages in the Ballerina website such as [3] and [4]. [2] explains when to use each word.
- The last link to the **Bindgen Tool** page is currently broken because the page ID is given wrong.  The same correction should be applied for the **Bindgen Tool** link in step 3.
- When adding a page name as a link, we do not add the article "the" before it. (This is also applicable to the links used in the next two paragraphs)

[2] https://writing-fundamentals-guide.readthedocs.io/en/latest/lesson2-commas/#using-that-vs-which
[3]  https://dev.ballerina.io/learn/by-example/variables-and-types/,
[4] https://dev.ballerina.io/learn/ballerina-specifications/

2. When a step title is given after "Step -", let's start it with a capital letter (e.g., "Step 1 - Write the Java code").

3. "Here, you have used four Java classes:" should end with a colon because it is a sentence that precedes a list.

4. The bullet points after "The bindgen tool generates bindings for:" should start with capital letters.

5. "You'll" is used in a couple of pages. Shall we change those to "you will" to avoid using contractions?

6. Shall we change "In this section, how to use the bindgen tool to generate Ballerina bindings for Java classes and how to use them was explained." as follows?

```suggestion
The above sections explain how to use the `bindgen` tool to generate Ballerina bindings for Java classes and how to use them.
```
7. In the last paragraph, the link to **Java interoperability**. Since this navigator item is a title and not a page, should we link to the first page under this title?

## Suggested label(s) (optional)
Website_Rewrite

**Comment by sm1990** [comment]
Fixed the broken links in https://dev.ballerina.io/

**Comment by praneesha** [comment]
1. Updated the following.

- Updated to "The `bindgen` is a CLI tool that eases the process of...".
- Updated the [`Variables and types` BBE](https://dev.ballerina.io/learn/by-example/variables-and-types/) via https://github.com/ballerina-platform/ballerina-distribution/pull/3054.
- Updated https://dev.ballerina.io/learn/ballerina-specifications/.
- Broken links are fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4919.
- Updated the links to "......see [Bindgen Tool](/learn/java-interoperability-guide/the-bindgen-tool/)".

2. Updated all 4 steps to start with a capital letter.
3. Added the colon.
4. Updated capital letters in the bullet points.
5. Changed `you'll` to `you will`.
6. Updated the suggestion.
7. Already fixed in https://github.com/ballerina-platform/ballerina-dev-website/pull/4919/files.
