### ISSUE TITLE
Update sentence case in newsletter template

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6485]
## Description
Update sentence case in all titles of the newsletter template.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by dinushan20** [comment]
I updated the titles in sentence case in sample newsletter template in Pardot as follows.

Also please note usually creating new newsletter, we change all titles and as per the content doc shared with us since sometimes order and items are change. 

![image](https://user-images.githubusercontent.com/73055030/226797841-807accf4-dd00-4a1a-96ad-5138dcf8dec2.png)

**Comment by praneesha** [comment]
Closing as this is done as per the above comment.
