### ISSUE TITLE
Invalid code segments in Coding Converntions page

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-dev-website#7010]
## Description
> ref: https://ballerina.io/learn/style-guide/coding-conventions/

Need to validate these samples. Came across an invalid syntax in match statement sample

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by MaryamZi** [comment]
The invalid syntax is in https://ballerina.io/learn/style-guide/statements/. The last two points.

Few other things we can possibly change

- avoid using parentheses in conditions (`(i == 1)`) unless absolutely necessary and union types (`(int|error)`)
- use the optional type syntax - `int?` instead of `int|()`
- https://ballerina.io/learn/style-guide/operators-keywords-and-types/ - last point ("When accessing a function, object, class or record from another module, do not keep spaces around :.") is unnecessary now since the user can't have spaces around `:` in a qualified identifier
- better to avoid boolean literals in conditions due to unreachability changes (`if true`)
- avoid the tainted/untainted annotations
- https://ballerina.io/learn/style-guide/annotations-documentation-and-comments/#comments - Use // for both single-line and multi-line comments. - doesn't quite make sense since there is no alternative

**Comment by praneesha** [comment]
1. Done
2. Done
3. Removed
4. Done
5. 
6. Removed
