### ISSUE TITLE
ballerinax/salesforce.bulk Learn Page code samples are incomplete

### ISSUE THREAD

**Issue by ShammiL** [ballerina-platform/ballerina-dev-website#8593]
## Description
> In the learn page for [`ballerinax/salesforce.bulk`](https://central.ballerina.io/ballerinax/salesforce.bulk/7.6.0), code samples provided are incomplete.

<img width="884" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/47134017/810909d9-092d-424e-9c29-e10a1670cb18">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
The issue occurs due to incorrect formatting in the `md` file.
@nipunayf  Please remove the empty lines before the code snippets (https://github.com/ballerina-platform/module-ballerinax-sfdc/blob/cb16c020fe0ce7328faf7aa7bb8de3d4abf555b9/ballerina/modules/bulk/Module.md?plain=1#L24 & https://github.com/ballerina-platform/module-ballerinax-sfdc/blob/cb16c020fe0ce7328faf7aa7bb8de3d4abf555b9/ballerina/modules/bulk/Module.md?plain=1#L50 )
