### ISSUE TITLE
GraphQL BBE : Why using underscores?

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8647]
## Description
$subject in [GraphQL service - Service interceptors](https://ballerina.io/learn/by-example/graphql-service-interceptors/) and [GraphQL service - Field interceptors](https://ballerina.io/learn/by-example/graphql-field-interceptors/)

<img width="1158" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/9d03cb28-4951-4b60-9d2c-7ce85caca65e">

**Comment by ThisaruGuruge** [comment]
This is a rendering bug. Underscores are used to italicize the characters. @sm1990 Any thoughts?

**Comment by sm1990** [comment]
@ThisaruGuruge we have used back-ticks on the either sides of the text (https://github.com/ballerina-platform/ballerina-distribution/blob/6e60f543f51fadde4f894f7e965f856debf4ded3/examples/graphql-service-interceptors/graphql_service_interceptors.md?plain=1#L3). Thus the text is rendered as a code instead of an italicized text. I removed the back-ticks and tested it. The following is the output.
![output-onlinejpgtools](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/289d4c58-f7df-4c07-8aba-657781591296)

**Comment by ThisaruGuruge** [comment]
@DimuthuMadushan Any idea why we have used backticks here? If it is not necessary, shall we remove them?

**Comment by DimuthuMadushan** [comment]
It was mistakenly added as a review suggestion. I'll fix this.
