### ISSUE TITLE
Useful links in the dayforce connector Readme is shown as `[Useful links](#useful-links)`

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-dev-website#9062]
## Description
Please take a look at the image.

<img width="1177" alt="Screenshot 2024-06-07 at 14 38 41" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11239305/d580bc6f-9eb4-48ce-af73-17cd879b565d">

I have the Readme `Useful links` as follows 
https://github.com/ballerina-platform/module-ballerinax-dayforce?tab=readme-ov-file#useful-links

**Comment by sm1990** [comment]
@Bhashinee the docs are generated using the `module.md`. The issue occurs due to incorrect formatting used in the `md` (https://github.com/ballerina-platform/module-ballerinax-dayforce/blob/6b0deea07da8c46821beec4140579d6be4d637a8/ballerina/Module.md?plain=1#L83).
There is no need to make the heading a link in the `md.` The link is created during the `md -> html` conversion.

You have to update the `md` and re-release the module.
