### ISSUE TITLE
BBE tests fail intermittently while verifying the output 

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-dev-website#9286]
**Description:**

$title

In the output verification of the BBEs, it may fail intermittently due to the "standard-library-module pulled from central successfully" lines.

Eg:
```
ballerina/regex:1.4.3 pulled from central successfully
```
See https://scans.gradle.com/s/pmtj2vrtv5pto/console-log?task=:ballerina:testExamples#L55.

I have observed this more than one time, and it is better if we do the output verification handling those cases also, so that it does not take a longer time for the CI Ubuntu full build to pass with these intermittent failures.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
This issue happens when we do not update the latest version of library modules in the distribution repo. When we run the example and verify the output, the first line is to pull the latest module from the central. That leads to failure of the output verification. In the library development process, we mention updating the distribution once we do a release[1]. If the distribution fails due to this, it is the module owner's responsibility 

1. https://github.com/ballerina-platform/ballerina-library/blob/main/docs/build-and-release-guide.md#single-module-release
