### ISSUE TITLE
Add security BBEs for WebSub

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-dev-website#9364]
**Description:**
Need to write security BBEs for WebSub.

**Comment by daneshk** [comment]
@ayeshLK can you check this

**Comment by ayeshLK** [comment]
According to the WebSub spec [1] there are three main entities associated with this protocol.
1. Publisher
2. Subscriber
3. Hub

Hence, there are three flows we have to consider when describing the security.
- Publisher to Hub
- Subscriber to Hub
- Hub to Subscriber

`Subscriber` to `Hub` flow can have a security mechanism and this is currently captured in the `Consume GitHub events` [2] BBE in WebSub subscriber perspective. But, currently we have not written a BBE to capture this requirement from the WebSub hub perspective as writing a hub is not quite straightforward and writing a WebSub hub has a less than 20% probability. Hence, we decided to implement a fully fledged WebSub hub implementation with security involved and this is currently completed [3]

If we take the `Publisher` to `Hub` flow, this is not comprehensively described in the WebSub spec and we have written a customized protocol to capture this flow. This is also captured in WebSub hub [4] example which is included in the repository.

Apart from the above, WebSub does not define additional security mechanism in the `Hub` to `Subscriber` flow. So, we do not need a BBE to capture this flow.

@NipunaRanasinghe highly appreciate your input on how we could proceed on this.

[1] - https://www.w3.org/TR/websub/#high-level-protocol-flow
[2] - https://ballerina.io/learn/by-example/websub-webhook-sample/
[3] - https://github.com/ballerina-platform/module-ballerina-websubhub/tree/main/examples/kafka-hub
[4] - https://github.com/ballerina-platform/module-ballerina-websubhub/tree/main/examples/kafka-hub/publisher

**Comment by NipunaRanasinghe** [comment]
@ayeshLK I agree that there’s no need to focus on the Hub to Subscriber and Subscriber to Hub flows for now, as the former doesn't require any special protocol and the latter is already covered well.

However, IMO it might be worth exploring the addition of a BBE for the Publisher to Hub scenario. Instead of implementing a complete hub within the BBE (which could make it quite lengthy), probably we could simplify it by using our publisher to publish to a public, well-known hub. This way, we can provide a clear example without overcomplicating the BBE. Shall we look into the possibility of that?
